# Generated by Django 5.0.7 on 2024-07-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0002_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='location',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='login',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='login',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='name',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
