# Generated by Django 5.0.7 on 2024-07-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0003_rename_location_login_password_remove_login_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='login_id',
            field=models.IntegerField(default=1),
        ),
    ]
